export const listOfCars = [
    {
        brand: "Toyota",
        model: "Camry",
        volume: 3.5,
        condition: "good",
        image: "images/1.jpg",
        type: "Седан",
        carClass: "vip",
        year: 2019,
        price: 9000,
        index: 1
    },
    {
        brand: "BMW",
        model: "M5",
        volume: 4.4,
        condition: "Perfect",
        image: "images/2.jpg",
        type: "Седан",
        carClass: "vip",
        year: 2021,
        price: 20000,
        index: 2
    },
    {
        brand: "Mercedes",
        model: "cls",
        volume: 6.3,
        condition: "Perfect",
        image: "images/3.jpg",
        type: "Седан",
        carClass: "vip",
        year: 2020,
        price: 20000,
        index: 3
    },
    {
        brand: "Honda",
        model: "Fit",
        volume: 1.3,
        condition: "Average",
        image: "images/4.jpg",
        type: "Хэтчбек",
        carClass: "eco",
        year: 2003,
        price: 800,
        index: 4
    },
    {
        brand: "Daewoo",
        model: "Matiz",
        volume: 0.8,
        condition: "Perfect",
        image: "images/5.jpg",
        type: "Хэтчбек",
        carClass: "eco",
        year: 2007,
        price: 600,
        index: 5
    },
    {
        brand: "Daewoo",
        model: "Nexia",
        volume: 1.6,
        condition: "good",
        image: "images/6.jpg",
        type: "Седан",
        carClass: "eco",
        year: 2012,
        price: 800,
        index: 6
    },
    {
        brand:"Lexus",
        model:"LX570",
        volume: 5.7,
        condition: "good",
        image: "images/7.jpg",
        type: "Кроссовер",
        carClass: "vip",
        year: 2018,
        price: 20000,
        index: 7
    },
    {
        brand:"Hyundai",
        model:"Sonata",
        volume: 2.0,
        condition: "perfect",
        image: "images/8.jpg",
        type: "Седан",
        carClass: "average",
        year: 2014,
        price: 4000,
        index: 8
    },
    {
        brand:"Mercedes",
        model:"g63",
        volume: 6.3,
        condition: "perfect",
        image: "images/9.jpg",
        type: "Кроссовер",
        carClass: "vip",
        year: 2018,
        price: 20000,
        index: 9
    },
    {
        brand:"Lexus",
        model:"LX470",
        volume: 4.7,
        condition: "good",
        image: "images/10.jpg",
        type: "Кроссовер",
        carClass: "vip",
        year: 2010,
        price: 13000,
        index: 10
    },
    {
        brand:"Toyota",
        model:"Supra",
        volume: 3.0,
        condition: "perfect",
        image: "images/11.jpg",
        type: "Седан",
        carClass: "retro",
        year: 1996,
        price: 20000,
        index: 11
    },
    {
        brand:"Nissan",
        model:"Skyline",
        volume: 2.5,
        condition: "perfect",
        image: "images/12.jpg",
        type: "Седан",
        carClass: "retro",
        year: 1998,
        price: 20000,
        index: 12
    },
    {
        brand: "Mercedes",
        model: "Sprinter",
        volume: 2.2,
        condition: "avarege",
        image: "images/13.jpg",
        type: "Грузовое",
        carClass: "average",
        year: 2000,
        price: 5000,
        index: 13
    },
    {
        brand: "Suzuki",
        model: "GSX-R 750",
        volume: 0.75,
        condition: "perfect",
        image: "images/14.JPG",
        type: "Мотоцикл",
        carClass: "average",
        year: 2014,
        price: 3000,
        index: 14
    },
    {
        brand: "Man",
        model: "12",
        volume: 12,
        condition: "avarege",
        image: "images/15.jpg",
        type: "Грузовое",
        carClass: "average",
        year: 1998,
        price: 6000,
        index: 15
    }
]
